import Navbar from "./components/Navbar";
import "./globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Blog - Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark:bg-black dark:text-white min-h-screen">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
